# Generated by Django 2.1.1 on 2018-09-23 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='firstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
