# Generated by Django 2.1.1 on 2018-09-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180923_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='phone_number',
        ),
    ]
