# Generated by Django 2.1.1 on 2018-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180923_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
